# Generated by Django 3.2.6 on 2021-08-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210805_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='groups',
        ),
        migrations.AddField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(to='main.StudentGroup', verbose_name='Группы'),
        ),
    ]
