# Generated by Django 3.2.6 on 2021-08-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210805_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(related_name='students', to='main.StudentGroup', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='groups',
            field=models.ManyToManyField(related_name='teachers', to='main.StudentGroup', verbose_name='Группы'),
        ),
    ]
